

const PrivacyPolicy = () => {
  return (
    <section className="pt-24">
      {/* Banner Section */}
      <div className="bg-[url('/faq-banner.jpg')] relative bg-cover h-[250px] lg:h-[400px]">
        <div className="absolute inset-0 bg-black opacity-50"></div>
        <div className="relative z-10 flex justify-center items-center h-full">
          <div className="text-white  font-bold text-2xl lg:text-4xl uppercase">
            Privacy Policy & Cookies | Tasty Drop
          </div>
        </div>
      </div>

      {/* Policy */}
      <div className="mx-auto w-full max-w-3xl text-sm text-justify pt-20 pb-36 text-black/80">
        <p>
          <p className="my-4">
            This policy explains how we, Tasty Drop, a brand of {""}
            <strong className="text-pink">https://tasty-drops.web.app</strong> , use your personal
            information which you provide to us when using our service,
            including but not limited to our website and mobile applications
            (apps)
          </p>
          <p className="font-bold ">What information we collect about you?</p>
          <p className="my-4">
            We collect personal information from you when you order goods or
            services from us or use our website. We also collect information
            when you complete any customer survey. Website usage information may
            also be collected using cookies.
          </p>
          <p className="font-bold ">Cookies and Google Analytics</p>
          <p className="my-4">
            Cookies are small text files that are placed on your computer by
            websites that you visit. They are widely used in order to make
            websites work, or work more efficiently, as well as to provide
            information to the owners of the site.
          </p>
          <p className="my-4">
            This website uses Google Analytics, a web analytics service provided
            by Google, Inc. {("Google")}. Google Analytics uses {"cookies"}, which
            are text files saved on your computer, to help the website analyze
            how you use the site. The information generated by the cookie about
            your use of the website will be transmitted to and stored by Google
            on servers in the United States. If this website anonymizes IP
            addresses, your IP address will be truncated by Google within a EU
            member state or other EEA state before being transmitted to the US.
            Only in exceptional situations will your full IP address be
            transmitted to Google servers in the United States and truncated
            there. Google will use this information for the purpose of
            evaluating your use of the website, compiling reports on website
            activity for website operators and providing other services relating
            to website activity and internet usage. Google will not associate
            your IP address with any other data held by Google. You may refuse
            the use of cookies by selecting the appropriate settings on your
            browser, however please note that if you do this you may not be able
            to use the full functionality of this website. By using this
            website, you consent to the processing of data about you by Google
            in the manner and for the purposes set out above.
          </p>
          <p className="font-bold ">
            How will we use the information we collect from you?
          </p>
          <p className="my-4">
            Information that we collect from you is used to process your order
            and to manage your account. We may also use your information to
            email you about other products or services that we think may be of
            interest to you.
          </p>
          <p className="my-4">
            In processing your order we may send your information to credit
            reference and fraud prevention agencies.
          </p>
          <p className="my-4">
            From time to time we may send your information to third parties
            which we consider may have goods or services which are of interest
            to you. If you do not wish to be contacted by third parties please
            reach out to us through our in-app customer support chat feature on
            Help Center.
          </p>
          <p className="font-bold ">Access to your information</p>
          <p className="my-4">
            You have a right to request a copy of the information we hold on you
            at any time. Please reach out to us through our in-app customer
            support chat feature on Help Center if you would like to receive a
            copy of this information. There will be a small charge for
            processing this request.
          </p>
          <p className="font-bold ">Other Websites</p>
          <p className="my-4">
            Our website may have links to other websites. This privacy policy
            only applies to this website. You should therefore read the privacy
            policies of the other websites when you are using those sites.
          </p>
        </p>
      </div>
    </section>
  );
};

export default PrivacyPolicy;